version: "3.3"

services:
  db:
    build: db
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
  dac:
    build: .
    depends_on:
      - db
    ports:
      - '8080:8080'
