version: "3.3"

services:
  db:
    build:
      context: db
      args:
      - SA_PASSWORD=${DATABASE_PASSWORD}
    environment:
      - SA_PASSWORD=${DATABASE_PASSWORD}
      - ACCEPT_EULA=Y
  dac:
    build:
      context: .
      args:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
    ports:
      - '8080:8080'
